### ISSUE TITLE
How can I use this extension in VSCode?

### ISSUE THREAD

**Issue by WIZeaz** [psucodervn/cfhelper#5]
I download this extension on my VSCode, but I don't know how to use, because of no instruction or guide.
Could you add some guide or welcome page on this extension?

**Comment by psucodervn** [comment]
Hello, thanks for asking. Unfortunately, I've abandon this project and haven't use this extension for a long time, and I'm not sure it could work now. I will check and write an instruction if it works :)

p/s: In the meantime, you can try some others extension such as [ICIE](https://marketplace.visualstudio.com/items?itemName=pustaczek.icie) (I haven't try it yet, but it seems to have many helpful features)
